[package]
name = "tc-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
asm-compiler = { path = "./asm-compiler" }
hl-compiler = { path = "./hl-compiler" }
emulator = { path = "./emulator" }